### ISSUE TITLE
sudo dnf install gpaste-client    >  Error: Unable to find a match: gpaste-client

### ISSUE THREAD

**Issue by tuxedotje** [blackjackshellac/clippie#5]
Good job to make gpaste work for gnome 40.

sudo dnf install gpaste-client  
does give an error
No match for argument: gpaste-client
Error: Unable to find a match: gpaste-client

**Comment by blackjackshellac** [comment]
Oops, should be `sudo dnf install gpaste`

**Comment by blackjackshellac** [comment]
I've left a strongly worded note in the cubbyhole of the QA team lead.  Hopefully this kind of slip-up will avoided in the future.
