### ISSUE TITLE
clippy does not remain open. 

### ISSUE THREAD

**Issue by tuxedotje** [blackjackshellac/clippie#6]
when in gnome 40 (Fedora34) set clippie to open it does (in https://extensions.gnome.org/local/)
But I expect something visible, and that is not there. maybe I should see a sign on TopBar?
And when I return to https://extensions.gnome.org/local/ clipppie is not open. 
O these are 2 questions.

**Comment by blackjackshellac** [comment]
Do you see it in gnome-extensions?  It should be installed in ~/.local/share/gnome-shell/extensions.  The icon should look like this,

![image](https://user-images.githubusercontent.com/825403/114983143-3ea44700-9e5e-11eb-9da2-986f489b019b.png)

I just tested the github version on a new user and it seems fine.  Did you install from gnome.extensions.org or here?

**Comment by tuxedotje** [comment]
I did both installations. Same result.
Gpaste is not working in gnome 40??? Could that be the case?
Thanks

**Comment by blackjackshellac** [comment]
I'm using it with gnome 40 on Fedora 34 beta.  gpaste uses gtk3 currently but that is available.

```
$ uname -a
Linux doont 5.11.13-300.fc34.x86_64 #1 SMP Sun Apr 11 15:07:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ gnome-shell --version
GNOME Shell 40.0
```

Did you try logging out and logging back in again after the github install?

**Comment by blackjackshellac** [comment]
I tested the github version on both X11 and Wayland, and both are fine.

Maybe gpaste daemon isn't currently running,

```
$ gsettings get org.gnome.GPaste track-changes
true
# if false, set it to true (this can be done in the clippie Preferences dialog on the github version)
$ gsettings set org.gnome.GPaste track-changes true
$ gpaste-client daemon-reexec
```

**Comment by blackjackshellac** [comment]
Also, you can check that gpaste-client is tracking changes copying some text and then running,

```
$ gpaste-client
0e2e8725-e763-4a41-b761-3814ef53eec1: org.gnome.GPaste track-changes
369d9b3f-2123-45bb-b636-593557818062: gsettings get org.gnome.GPaste track-changes
5ba2cba1-555a-4741-aced-ecf4a6d063ca: dnf repoquery --alldeps --whatrequires
00a9c53b-6a04-4e8d-baef-a9a0266a39c3: $ uname -a
Linux doont 5.11.13-300.fc34.x86_64 #1 SMP Sun Apr 11 15:07:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ gnome-shell --version
GNOME Shell 40.0
...
```

**Comment by blackjackshellac** [comment]
Might also help to turn on debugging in the extension and then follow the output with journalctl,

```
$ gsettings --schemadir ~/.local/share/gnome-shell/extensions/clippie@blackjackshellac.ca/schemas  get org.gnome.shell.extensions.clippie-blackjackshellac debug
false
$ gsettings --schemadir ~/.local/share/gnome-shell/extensions/clippie@blackjackshellac.ca/schemas set org.gnome.shell.extensions.clippie-blackjackshellac debug true
$ journalctl -f 
Apr 16 04:37:23 doont gnome-shell[8070]: DEBUG: [cl_menus] menu open=true
Apr 16 04:37:23 doont gnome-shell[8070]: DEBUG: [cl_menus] Refreshing all menu items
Apr 16 04:37:23 doont gnome-shell[8070]: DEBUG: [cl_ippie] Found lock entry uuid=372bfdff-9f59-495e-b4ff-339265eb0d71
Apr 16 04:37:23 doont gnome-shell[8070]: DEBUG: [cl_ippie] Found lock entry uuid=8bdcf4cf-af25-4989-8273-3d70109ef3b8
```
Thanks.

**Comment by blackjackshellac** [comment]
maybe this is related

https://github.com/Keruspe/GPaste/issues/349#issuecomment-821053657

 (are you running Fedora 34?)

I tried removing gpaste and its dependencies and reinstalling and it also asks for gpaste-ui.

```
dnf install gpaste gpaste-ui gpaste-libs
```

The other thing you could try is to run `journalctl -f` in a terminal and then try to start the extension at gnome.extensions.org. That might give me some useful information.

**Comment by blackjackshellac** [comment]
I just tested with only gpaste and gpaste-libs on a fresh install and installed from extensions.gnome.org and it enabled and I could see the panel indicator icon.  It took a while to initialize but got going after about 10 seconds.  The version from github worked as expected as well.

Let me know if you find anything else.

Thanks

**Comment by tuxedotje** [comment]
journalctl  results
[clippie.txt](https://github.com/blackjackshellac/clippie/files/6324609/clippie.txt)
Gpaste is working, but no TopBar  signs of Clippie or Gpaste. 
Thanks

**Comment by blackjackshellac** [comment]
This seems to be the culprit (from your log output) for why gpaste isn't working,

```
Apr 16 13:37:06 Asus gnome-shell[1667]: Received error from D-Bus search provider org.gnome.GPaste.Ui.desktop: 
 Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface
 “org.gnome.Shell.SearchProvider2” on object at path /org/gnome/GPaste/SearchProvider
```

which looks a lot like that gpaste issue that I referenced earlier.

What happens if you run gpaste-client at the command line?
